---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/guesses":
    get:
      summary: List all Guesses
      tags:
      - Guesses
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
    post:
      summary: Create new Guess
      tags:
      - Guesses
      parameters: []
      responses:
        '201':
          description: successful
        '422':
          description: unprocessable entity
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                latitude:
                  type: number
                  format: float
                longitude:
                  type: number
                  format: float
              required:
              - latitude
              - longitude
  "/api/guesses/{id}":
    get:
      summary: Get Guess by ID
      tags:
      - Guesses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
        '404':
          description: not found
  "/api/sessions":
    post:
      summary: Create session
      tags:
      - Sessions
      parameters: []
      responses:
        '201':
          description: successful
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
              - password_confirmation
  "/api/treasures":
    get:
      summary: List all treasure locations
      tags:
      - Treasures
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
    post:
      summary: Create new Treasure
      tags:
      - Treasures
      parameters: []
      responses:
        '201':
          description: successful
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                latitude:
                  type: bigdecimal
                longitude:
                  type: bigdecimal
                active:
                  type: boolean
              required:
              - name
              - latitude
              - longitude
  "/api/treasures/{id}":
    put:
      summary: Update resource
      tags:
      - Treasures
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                latitude:
                  type: bigdecimal
                longitude:
                  type: bigdecimal
                active:
                  type: boolean
              required:
              - name
              - latitude
              - longitude
    get:
      summary: get treasure location
      tags:
      - List Treasures
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
  "/api/users":
    get:
      summary: List all users
      tags:
      - Users
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
    post:
      summary: Create new User
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: successful
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - email
              - password
              - password_confirmation
  "/api/users/{id}":
    put:
      summary: Update user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
    get:
      summary: Get User
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
  "/api/winners":
    get:
      summary: List winners
      tags:
      - Winners
      parameters:
      - name: page
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
- bearerAuth: []
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
