---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/guesses":
    get:
      summary: List all Guesses
      tags:
      - Guesses
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
  "/api/guesses/{id}":
    get:
      summary: Get Guess by ID
      tags:
      - Guesses
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
        '404':
          description: not found
  "/api/treasure_locations":
    get:
      summary: List all treasure locations
      tags:
      - Treasure Locations
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
    post:
      summary: create new resource
      tags:
      - Treasure Locations
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '201':
          description: successful
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                latitude:
                  type: bigdecimal
                longitude:
                  type: bigdecimal
                active:
                  type: boolean
              required:
              - name
              - latitude
              - longitude
  "/api/treasure_locations/{id}":
    put:
      summary: Update resource
      tags:
      - Treasure Locations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                latitude:
                  type: bigdecimal
                longitude:
                  type: bigdecimal
                active:
                  type: boolean
              required:
              - name
              - latitude
              - longitude
    get:
      summary: get treasure location
      tags:
      - Treasure Locations
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
  "/api/users":
    get:
      summary: List all users
      tags:
      - Users
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
    post:
      summary: create new user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: successful
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - email
              - password
              - password_confirmation
  "/api/users/{id}":
    put:
      summary: Update user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
    get:
      summary: get user
      tags:
      - Users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
  "/api/winners?page=1":
    get:
      summary: List winners
      tags:
      - Winners
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
